language: csharp
mono:
  - latest
install:
  - curl -sSl https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnu restore
script:
  - dnx /home/travis/build/bagocius/dnx-templates/test/dnx-templates.tests/project.json test -parallel none